PATCH http://localhost:3000/posts
Content-Type:application/json
{
    "id": 7,
    "title": "what's new with type script",
    "postType": "post",
    "status": "draft",
    "content": "test content",
    "metaOptions": {
        "metaValue": {
            "sidebarEnabled": true,
            "footerActive": true
        }
    },
    "tags": [1, 6]
}